# Generated by Django 2.1 on 2018-08-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20180814_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_nature',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
